spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: calorietracker
    password: ${DB_PASSWORD}
  jpa:
    hibernate.ddl-auto: validate
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints.web.exposure.include: health,info,prometheus,metrics
  tracing.sampling.probability: 1.0
  zipkin.tracing.endpoint: http://localhost:9411/api/v2/spans
